### ISSUE TITLE
Build on FreeBSD 11

### ISSUE THREAD

**Issue by petr-fischer** [tagattie/FreeBSD-VSCode#1]
I tried to build your port on the FreeBSD 11.2-RELEASE-p9, everything looks OK (minor issues with yarn and required node version >= 8 and <=10).

But when I run code-oss, this error occurs:
```
/usr/local/bin/code-oss: Undefined symbol "fstat@FBSD_1.5"
```
Do you have an idea what's wrong? Thanks!

**Comment by tagattie** [comment]
Hi, thanks for your interest in this port.

code-oss is actually a copy of the electron downloaded from my FreeBSD-Electron port repository. The error I guess is due to symbol version mismatch since the downloaded electron is built on FreeBSD 12.

Building both electron and vscode (as follows) on FreeBSD 11 may help:

- Clone [electron port repo](https://github.com/tagattie/FreeBSD-Electron)
- Build electron with port option DIST on
  - dist.zip will be generated in the directory ${WRKSRC}/out/Release
- Place the dist.zip file in the DISTDIR (e.g. /usr/ports/distfiles) as electron-v4.1.2-freebsd-x64.zip
- Update vscode port's distinfo by `make makesum` in the vscode port directory
- Retry vscode build

**Comment by petr-fischer** [comment]
Thanks for tips! Electron build failed:
```
...
Skipped patch 'src/ostreams.h'.
Skipped patch 'include/v8-platform.h'.
Skipped patch 'src/api.cc'.
Skipped patch 'src/heap/heap.cc'.
Skipped patch 'test/unittests/base/bits-unittest.cc'.
Skipped patch 'BUILD.gn'.
Skipped patch 'BUILD.gn'.
Skipped patch 'BUILD.gn'.
===>  Applying FreeBSD patches for electron-4.1.4
1 out of 4 hunks failed--saving rejects to base/BUILD.gn.rej
=> FreeBSD patch patch-base_BUILD.gn failed to apply cleanly.
=> Patch(es)  patch-BUILD.gn patch-apps_ui_views_app__window__frame__view.cc patch-ash_display_mirror__window__controller.cc applied cleanly.
*** Error code 1

Stop.
make[1]: stopped in /usr/home/pf/src/ports/FreeBSD-Electron
*** Error code 1

Stop.
make: stopped in /usr/home/pf/src/ports/FreeBSD-Electron
```

But I rather update to FreeBSD 12 :)

**Comment by tagattie** [comment]
If your port working directory (`work`) is under `FreeBSD-Electron`, temporarily renaming `.git` directory to some other name (e.g. `.git.bak`) and retrying build may help.

The `git apply` command, which is used in the pre-patch phase of the port, have some problem applying patches to files under subdirectories of a git repository.

**Comment by tagattie** [comment]
Now it should build on both FreeBSD 11 and 12.

**Comment by petr-fischer** [comment]
You even prebuild a package for FreeBSD 11! I must say - **thanks**! Works prefectly.
